"""Kernel generators, imported for the side effect of registering them."""

from fnnx.extras.compilers.c.onnx.ops import (  # noqa: F401
    activations,
    attention,
    casts,
    conv,
    cumulative,
    einsum,
    elementwise,
    gather,
    gemm,
    generate,
    linear_attention,
    logic,
    loss,
    ml,
    normalization,
    pad,
    pool,
    quantize,
    recurrent,
    reduce,
    resize,
    sampling,
    scatter,
    signal,
    softmax,
    svm,
    tfidf,
    tree,
    views,
)
