"""Rendering a planned program as one self-contained, STB-style C99 header."""

from __future__ import annotations

from collections.abc import Iterable, Iterator

from onnx import TensorProto
from onnx.numpy_helper import to_array

from fnnx import __version__
from fnnx.extras.compilers.c.onnx.codegen import (
    IOTensor,
    LabelTable,
    Program,
    StaticBuffer,
)
from fnnx.extras.compilers.c.onnx.dtypes import c_type, element_size, numpy_dtype_name
from fnnx.extras.compilers.c.onnx.emit import (
    INVALID_ARGUMENT_STATUS,
    comment_safe,
    initializer_lines,
    scalar_literal,
    string_literal,
)
from fnnx.extras.compilers.c.onnx.loader import display_domain


def render_header(program: Program) -> str:
    """The complete `<prefix>.h` text: declarations, then a guarded implementation."""
    upper = program.prefix.upper()
    lines: list[str] = [
        *_preamble(program),
        f"#ifndef {upper}_H_INCLUDED",
        f"#define {upper}_H_INCLUDED",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        *_status_enum(program),
        *_footprint_macros(program),
        *_runtime_dim_macros(program),
        *_io_macros(program),
        *_label_declarations(program),
        *_entry_declarations(program),
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        f"#endif /* {upper}_H_INCLUDED */",
        "",
        f"#ifdef {upper}_IMPLEMENTATION",
        f"#ifndef {upper}_IMPLEMENTATION_INCLUDED",
        f"#define {upper}_IMPLEMENTATION_INCLUDED",
        "",
        "#include <math.h>",
        "#include <stddef.h>",
        "#include <string.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        *_label_definitions(program),
        *_weight_definitions(program),
        *_scratch_definitions(program),
        *_kernel_definitions(program),
        *_entry_definitions(program),
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        f"#endif /* {upper}_IMPLEMENTATION_INCLUDED */",
        f"#endif /* {upper}_IMPLEMENTATION */",
    ]
    return "\n".join(lines) + "\n"


def buffer_bytes(buffers: Iterable[StaticBuffer]) -> int:
    return sum(
        buffer.declared_count * element_size(buffer.elem_type) for buffer in buffers
    )


def _preamble(program: Program) -> list[str]:
    upper = program.prefix.upper()
    opsets = ", ".join(
        f"{display_domain(domain)}={version}"
        for domain, version in sorted(program.opsets.items())
    )
    bindings = (
        ", ".join(
            f"{name}={value}" for name, value in sorted(program.dim_bindings.items())
        )
        or "none"
    )
    weights = buffer_bytes(program.weights)
    arena = buffer_bytes(program.scratch)
    per_node = (
        [f" * `{program.prefix}_node_<id>_run` runs one node on the caller's buffers."]
        if program.nodes
        else []
    )
    return [
        "/*",
        f" * {program.prefix}.h - generated by FNNX {__version__} "
        "(fnnx.extras.compilers.c)",
        f" * from {comment_safe(program.source)}.",
        " *",
        " * Self-contained C99 inference code: no dynamic allocation, no I/O, "
        + ("every buffer" if program.runtime_dims else "every shape"),
        " * "
        + ("sized" if program.runtime_dims else "fixed")
        + " at compile time, and libm the only thing to link against. Builds clean",
        " * under -std=c99 -Wall -Wextra -Werror -Werror=vla.",
        " *",
        " * Usage: include this header wherever the declarations are needed, and in exactly",
        " * one translation unit ask for the implementation as well:",
        " *",
        f" *     #define {upper}_IMPLEMENTATION",
        f' *     #include "{program.prefix}.h"',
        " *",
        f" * `{program.prefix}_run` runs the whole model, returning {upper}_OK on success.",
        *per_node,
        " * Every buffer is caller-provided, contiguous and row-major, of exactly the shape",
        f" * the {upper}_* macros below describe.",
        *_runtime_dim_preamble(program),
        " *",
        " * Not reentrant: the implementation owns static scratch buffers, so at most one",
        " * call per compiled model may be in flight at a time.",
        " *",
        f" * Static memory: {weights + arena} bytes "
        f"({weights} of weights, {arena} of scratch)",
        f" * Opset imports: {opsets}",
        f" * Dimension bindings: {bindings}",
        *_runtime_dim_summary(program),
        " */",
    ]


def _runtime_dim_preamble(program: Program) -> list[str]:
    if not program.runtime_dims:
        return []
    upper = program.prefix.upper()
    listed = ", ".join(f"`{dim.c_name}`" for dim in program.runtime_dims)
    return [
        " *",
        f" * Runtime dimensions: every entrypoint takes {listed} ahead of its buffers, as",
        f" * the sizes this call works at. Each must lie in [1, {upper}_DIM_*_MAX]; outside",
        f" * that the call returns {upper}_{INVALID_ARGUMENT_STATUS} and writes nothing.",
        " * Buffers are sized for the maxima, but a call reads and writes only the leading",
        " * elements of the shape its dimension values give — the shape below is the",
        " * capacity, not what any one call passes.",
    ]


def _runtime_dim_summary(program: Program) -> list[str]:
    if not program.runtime_dims:
        return []
    listed = ", ".join(f"{dim.name}<={dim.maximum}" for dim in program.runtime_dims)
    return [f" * Runtime dimensions: {listed}"]


def _status_enum(program: Program) -> list[str]:
    upper = program.prefix.upper()
    return [
        "/* Status codes returned by the entrypoints. */",
        f"typedef enum {program.prefix}_status {{",
        f"    {upper}_OK = 0,",
        f"    {upper}_{INVALID_ARGUMENT_STATUS} = 1",
        f"}} {program.prefix}_status;",
        "",
    ]


def _footprint_macros(program: Program) -> list[str]:
    upper = program.prefix.upper()
    weights = buffer_bytes(program.weights)
    arena = buffer_bytes(program.scratch)
    return [
        "/* Static memory footprint, in bytes: constant data, scratch space, and the sum. */",
        f"#define {upper}_WEIGHTS_BYTES {weights}",
        f"#define {upper}_ARENA_BYTES {arena}",
        f"#define {upper}_STATIC_BYTES {weights + arena}",
        "",
    ]


def _runtime_dim_macros(program: Program) -> list[str]:
    lines: list[str] = []
    for dim in program.runtime_dims:
        lines.append(
            f"/* Runtime dimension `{comment_safe(dim.name)}`: the largest value the "
            f"`{dim.c_name}` parameter may take. */"
        )
        lines.append(f"#define {dim.macro(program.prefix)} {dim.maximum}")
        lines.append("")
    return lines


def _io_macros(program: Program) -> list[str]:
    lines = _tensor_macros(program.inputs, program.outputs, owner="")
    for node in program.nodes:
        lines.extend(
            _tensor_macros(node.inputs, node.outputs, owner=f" of node `{node.id}`")
        )
    return lines


def _tensor_macros(
    inputs: Iterable[IOTensor], outputs: Iterable[IOTensor], *, owner: str
) -> list[str]:
    lines: list[str] = []
    for role, tensors in (("Input", inputs), ("Output", outputs)):
        for tensor in tensors:
            lines.append(
                f"/* {role} `{comment_safe(tensor.name)}`{comment_safe(owner)}: "
                f"{_tensor_label(tensor)}. */"
            )
            lines.append(f"#define {tensor.macro}_RANK {len(tensor.shape)}")
            lines.extend(
                f"#define {tensor.macro}_DIM_{axis} {size}"
                for axis, size in enumerate(tensor.shape)
            )
            lines.append(f"#define {tensor.macro}_COUNT {tensor.elem_count}")
            lines.append("")
    return lines


def _tensor_label(tensor: IOTensor) -> str:
    """The tensor's type, with any axis that scales named after the dimension it scales with."""
    if not tensor.runtime_shape:
        return _type_label(tensor.elem_type, tensor.shape)
    axes = [
        str(term.size)
        if term.dim is None
        else (term.dim if term.coefficient == 1 else f"{term.coefficient}*{term.dim}")
        for term in tensor.runtime_shape
    ]
    return (
        f"{numpy_dtype_name(tensor.elem_type)}[{', '.join(axes)}], "
        f"at most {_type_label(tensor.elem_type, tensor.shape)}"
    )


def _label_declarations(program: Program) -> list[str]:
    """The class-label tables, declared: metadata for the caller, not data any kernel reads.

    They carry external linkage rather than being `static` like the buffers below: they are
    part of what the artifact publishes, and a `static` array no emitted statement names
    would fail the header's own `-Wall -Werror` build contract.
    """
    lines: list[str] = []
    for table in program.labels:
        lines.append(
            f"/* Class labels of output `{comment_safe(table.tensor)}`, "
            f"one per element of its trailing axis. */"
        )
        lines.append(f"#define {table.macro} {len(table.values)}")
        lines.append(
            f"extern const {_label_c_type(table.elem_type)} "
            f"{table.symbol}[{table.macro}];"
        )
        lines.append("")
    return lines


def _label_definitions(program: Program) -> list[str]:
    lines: list[str] = []
    for table in program.labels:
        lines.append(
            f"const {_label_c_type(table.elem_type)} {table.symbol}[{table.macro}] = {{"
        )
        lines.extend(initializer_lines(_label_literals(table)))
        lines.append("};")
        lines.append("")
    return lines


def _label_literals(table: LabelTable) -> list[str]:
    if table.elem_type == TensorProto.STRING:
        return [string_literal(str(value)) for value in table.values]
    return [scalar_literal(value, table.elem_type) for value in table.values]


def _label_c_type(elem_type: int) -> str:
    return "char* const" if elem_type == TensorProto.STRING else c_type(elem_type)


def _entry_declarations(program: Program) -> list[str]:
    lines = [
        "/* Runs the whole model. Returns one of the status codes above. */",
        f"int {program.prefix}_run("
        f"{_signature(program, program.inputs, program.outputs)});",
        "",
    ]
    for node in program.nodes:
        lines.append(
            f"/* Runs node `{comment_safe(node.id)}` on buffers of the caller's own. */"
        )
        lines.append(
            f"int {node.symbol}({_signature(program, node.inputs, node.outputs)});"
        )
        lines.append("")
    return lines


def _entry_definitions(program: Program) -> list[str]:
    lines: list[str] = []
    # Node entrypoints first: the whole-model one calls them, and a reader follows the
    # header top to bottom.
    for node in program.nodes:
        lines.extend(
            _entry_definition(
                program, node.symbol, node.inputs, node.outputs, node.body
            )
        )
    lines.extend(
        _entry_definition(
            program,
            f"{program.prefix}_run",
            program.inputs,
            program.outputs,
            program.body,
        )
    )
    return lines


def _entry_definition(
    program: Program,
    symbol: str,
    inputs: tuple[IOTensor, ...],
    outputs: tuple[IOTensor, ...],
    body: Iterable[str],
) -> list[str]:
    lines = [f"int {symbol}({_signature(program, inputs, outputs)})", "{"]
    for statement in (*_dim_guard(program), *body):
        lines.extend(f"    {line}" if line else "" for line in statement.splitlines())
    lines.append(f"    return {program.prefix.upper()}_OK;")
    lines.append("}")
    lines.append("")
    return lines


def _dim_guard(program: Program) -> list[str]:
    """Refuse a dimension value outside the range the artifact was compiled for.

    First thing in every entrypoint, before a single buffer is written: a rejected call
    leaves the caller's outputs exactly as it found them.
    """
    if not program.runtime_dims:
        return []
    tests = " || ".join(
        f"{dim.c_name} < 1 || {dim.c_name} > {dim.macro(program.prefix)}"
        for dim in program.runtime_dims
    )
    status = f"{program.prefix.upper()}_{INVALID_ARGUMENT_STATUS}"
    return [f"if ({tests}) {{\n    return {status};\n}}"]


def _signature(
    program: Program, inputs: Iterable[IOTensor], outputs: Iterable[IOTensor]
) -> str:
    parameters = [f"int32_t {dim.c_name}" for dim in program.runtime_dims]
    parameters += [
        f"const {c_type(tensor.elem_type)}* {tensor.c_name}" for tensor in inputs
    ]
    parameters += [f"{c_type(tensor.elem_type)}* {tensor.c_name}" for tensor in outputs]
    return ", ".join(parameters) if parameters else "void"


def _weight_definitions(program: Program) -> list[str]:
    lines: list[str] = []
    for buffer in program.weights:
        literals = list(_literals(buffer))
        if not literals:
            literals = ["0"]
        lines.append(_buffer_comment("Initializer", buffer))
        lines.append(
            f"static const {c_type(buffer.elem_type)} "
            f"{buffer.symbol}[{buffer.declared_count}] = {{"
        )
        lines.extend(initializer_lines(literals))
        lines.append("};")
        lines.append("")
    return lines


def _scratch_definitions(program: Program) -> list[str]:
    lines: list[str] = []
    for buffer in program.scratch:
        lines.append(_buffer_comment("Intermediate", buffer))
        lines.append(
            f"static {c_type(buffer.elem_type)} "
            f"{buffer.symbol}[{buffer.declared_count}];"
        )
        lines.append("")
    return lines


def _kernel_definitions(program: Program) -> list[str]:
    lines: list[str] = []
    for function in program.functions:
        lines.extend(function.definition.splitlines())
        lines.append("")
    return lines


def _literals(buffer: StaticBuffer) -> Iterator[str]:
    assert buffer.tensor is not None
    values = to_array(buffer.tensor).reshape(-1).tolist()
    return (scalar_literal(value, buffer.elem_type) for value in values)


def _buffer_comment(role: str, buffer: StaticBuffer) -> str:
    note = (
        " (zero-element; C99 forbids a zero-length array)"
        if buffer.elem_count == 0
        else ""
    )
    return (
        f"/* {role} `{comment_safe(buffer.name)}`: "
        f"{_type_label(buffer.elem_type, buffer.shape)}{note}. */"
    )


def _type_label(elem_type: int, shape: tuple[int, ...]) -> str:
    return f"{numpy_dtype_name(elem_type)}[{', '.join(str(size) for size in shape)}]"
